# Generated by Django 3.0.8 on 2020-07-10 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='myForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(choices=[('CHO', 'Corporate Head Office'), ('CBO', 'Corporate Branch Office'), ('HO', 'Home Office'), ('CS', 'Co-Working Space'), ('CVO', 'Corporate Virtual Office')], max_length=3)),
                ('Incident_desc', models.TextField()),
                ('DateOfAcci', models.DateField()),
                ('TimeOfAcci', models.TimeField()),
                ('incident_loc', models.TextField()),
                ('initial_seve', models.CharField(choices=[('B', 'Bad'), ('S', 'serious'), ('U', 'unpleasant'), ('H', 'Harsh'), ('M', 'Mild')], max_length=1)),
                ('suspected_cause', models.TextField()),
                ('immediate_act', models.TextField()),
                ('incident_type', multiselectfield.db.fields.MultiSelectField(choices=[('EI', 'Environmental Incident'), ('I', 'Injury/Illness'), ('PD', 'Property Damage'), ('V', 'Vehicle'), ('M', 'Mild')], max_length=11)),
                ('reporeted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
