# Generated by Django 3.0.8 on 2020-07-11 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='DateOfAcci',
            field=models.DateField(verbose_name='Date Of Incident'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Incident_desc',
            field=models.TextField(verbose_name='Incident Description'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='Location',
            field=models.CharField(choices=[('CHO', 'Corporate Head Office'), ('CBO', 'Corporate Branch Office'), ('HO', 'Home Office'), ('CS', 'Co-Working Space'), ('CVO', 'Corporate Virtual Office')], max_length=3, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='TimeOfAcci',
            field=models.TimeField(verbose_name='Time Of Incident'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='immediate_act',
            field=models.TextField(verbose_name='Immediate Actions Taken'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='incident_loc',
            field=models.TextField(verbose_name='Incident Location'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='incident_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EI', 'Environmental Incident'), ('I', 'Injury/Illness'), ('PD', 'Property Damage'), ('V', 'Vehicle'), ('M', 'Mild')], max_length=11, verbose_name='Sub Incident Types'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='initial_seve',
            field=models.CharField(choices=[('B', 'Bad'), ('S', 'serious'), ('U', 'unpleasant'), ('H', 'Harsh'), ('M', 'Mild')], max_length=1, verbose_name='Initial Severity'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='reporeted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Reported By'),
        ),
        migrations.AlterField(
            model_name='myform',
            name='suspected_cause',
            field=models.TextField(verbose_name='Suspected Cause'),
        ),
    ]
